### ISSUE TITLE
I can't install.

### ISSUE THREAD

**Issue by FRDS** [BrandonCookeDev/smashgg.js#27]
My problem is simple, I can't install this package. Every time I tried it, it outputs the same stuff:
```js
npm ERR! Unexpected end of JSON input while parsing near '....10","moment":"^2.22.'
npm ERR! A complete log of this run can be found in:
npm ERR!     %APPDATA%\npm-cache\_logs\2018-11-16T07_55_58_306Z-debug.log
```
It only happens to this package, any other package installs just fine.

**Comment by BrandonCookeDev** [comment]
After working with @FRDS on Discord, we determined there was just a caching issue with his npm.
After running `npm cache clean --force` the error was resolved.

**Comment by BrandonCookeDev** [comment]
The following is a transcript of the conversation
```

cookiE [RecursionGG]Today at 10:32 PM
do you happen to have the full npm debug log?
or could you reproduce
FaradiseToday at 10:32 PM
I could just reproduce it
wait
Log File:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\agung\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--',
1 verbose cli   'save',
1 verbose cli   'smashgg.js' ]
2 info using npm@6.4.1
3 info using node@v8.11.3
4 verbose npm-session 1b0423384fd7e9de
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/save 290ms
8 silly pacote range manifest for save@^2.3.2 fetched in 328ms
9 http fetch GET 304 https://registry.npmjs.org/smashgg.js 1098ms (from cache)
10 silly fetchPackageMetaData error for smashgg.js@latest Unexpected end of JSON input while parsing near '....10","moment":"^2.22.'
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 2871ms
13 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '....10","moment":"^2.22.'
13 verbose stack     at JSON.parse (<anonymous>)
13 verbose stack     at parseJson (C:\Users\agung\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
13 verbose stack     at consumeBody.call.then.buffer (C:\Users\agung\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
13 verbose stack     at <anonymous>
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
14 verbose cwd E:\git\GarudaBot
15 verbose Windows_NT 10.0.17763
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\agung\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--" "save" "smashgg.js"
17 verbose node v8.11.3
18 verbose npm  v6.4.1
19 error Unexpected end of JSON input while parsing near '....10","moment":"^2.22.'
20 verbose exit [ 1, true ]
(edited)
npm:
npm install -- save smashgg.js
npm ERR! Unexpected end of JSON input while parsing near '....10","moment":"^2.22.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\agung\AppData\Roaming\npm-cache\_logs\2018-12-06T03_33_40_098Z-debug.log
I think it has a problem with another package that I installed. I haven't tried to install it on my other projects tho
cookiE [RecursionGG]Today at 10:36 PM
did you pull the github down or just create a new directory, npm init, and then try npm install --save smashgg.js

reading the log it seems like the latter?
because I just ran npm install smashgg.js in a directory and it worked fine. Same npm version
it seems like the or a package json is malformed
i say the or a as in The (my package json) or a (as in a dependency's package json)
FaradiseToday at 10:40 PM
Do you know where I could find this "malformed" JSON?
cookiE [RecursionGG]Today at 10:40 PM
so this is the package json in the repository and should be the same that is coming from npm
  "dependencies": {
    "bluebird": "^3.5.1",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "node-cache": "^4.2.0",
    "p-map": "^1.2.0",
    "request": "^2.87.0",
    "request-promise": "^4.2.2",
    "when": "^3.7.8",
    "winston": "^2.4.3"
  },
  "devDependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "chalk": "^2.4.1",
    "eslint": "^5.0.1",
    "mocha": "^5.2.0",
    "sinon": "^6.1.4"
  }

it seems to me the version you have or are receiving has the moment dependency but cuts off the minor version and the json content simply ends there?
right that's what I'm trying to figure out. 
are you just running npm install --save smashgg.js from a new directory?
FaradiseToday at 10:41 PM
yeah
Because it always happen with every new directory, I think the problem lies in my NPM itself
cookiE [RecursionGG]Today at 10:42 PM
might be a caching issue
FaradiseToday at 10:43 PM
but tbh I can' still wrap my head around "why only this package"
because I can still install other new package just fine.
cookiE [RecursionGG]Today at 10:44 PM
I am seeing something similar here:
https://github.com/vuejs-templates/webpack/issues/990
GitHub
npm ERR! Unexpected end of JSON input while parsing near '...nd-in...
npm ERR! Unexpected end of JSON input while parsing near '...nd-index-1.0.2.tgz" },' npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\web-01\AppData\Roaming\npm-c...

we could try npm cache clean --force
seems like they determined their issue was a cache problem. This may be different but it's worth a shot
FaradiseToday at 10:47 PM
Welp
it works now
@cookiE [RecursionGG]
cookiE [RecursionGG]Today at 10:47 PM
after clearing the cache?
FaradiseToday at 10:47 PM
Yeah
cookiE [RecursionGG]Today at 10:48 PM
sweet, I appreciate you taking the time to help me debug it
```
